[workspace]
members = [
        "transaction",
        "transaction-diesel",
        "transaction-stm",
        "transaction-diesel/examples/simple-crud"]

[replace]
"transaction:0.1.0" = { path = "transaction" }
"transaction-diesel:0.1.0" = { path = "transaction-diesel" }